Styling
BucherLara/Capstone-Project pull request #23
Opened 2022-12-05 13:17 UTC by BucherLara

2022-12-06 11:19 UTC, JessicaLoers requested changes
**HI @BucherLara ✌️** 
The number of my comments look worse than they are.   

- I would like to recommend that you test your style declaration in the dev tools - just click on and off the checkmarks - you will see that you don't need many styles. 

**A more important topic is this one** 👇
- Actually it's part of the PR but I highly recommend to never pass the state-setter (callback function e.g. `setFacilities`) to your components ☝️
- Rather place the `toggleBookmark` function from  `components/Facility/index.js` to `_app.js` and pass this function as a prop onToggleBookmark={toggleBookmark}

2022-12-06 11:19 UTC, JessicaLoers commented on components/Facility/index.js
>  `;
This component is screaming out to be outsourced in a single file like e.g.  `styled.card.js`, where all the styles for the "card' are located.  This applies to most of the styled components in this file.
Otherwise it becomes quickly confusing  🫣

I highly recommend to use relative units for the font, regarding the accessibility of your app.  Here is an [article from my personal hero Josh W. Comeau](https://www.joshwcomeau.com/css/surprising-truth-about-pixels-and-accessibility/#accessibility-considerations) 

I guess you could get rid of some properties - please test it in the dev tool 

```suggestion
const StyledList = styled.ul`
  text-align: left;
  padding: 0;
  font-size: 1rem;
  line-height: 1.3rem;
`;
```

2022-12-06 11:19 UTC, JessicaLoers commented on components/Facility/index.js
> +  margin-bottom: 30px;
In `StyledImage`  the border-radius is %, in this component the  border-radius is px - please be consistent in using units. 
```suggestion
  border-radius: ???;
  background-color: var(--secondary-color);
  box-shadow: 0 2px 10px 0 rgba(0, 0, 0, 0.1);
  padding: 30px;
  margin-bottom: 30px;
```

2022-12-06 11:19 UTC, JessicaLoers commented on components/Facility/index.js
> +          </div>
I guess you could remove rid of this `<div>`

```suggestion
```

2022-12-06 11:19 UTC, JessicaLoers commented on components/Facility/index.js
> +          <div>
I guess you could remove rid of this <div>
```suggestion

```

2022-12-06 11:19 UTC, JessicaLoers commented on components/Facility/index.js
> +                  </svg>
I get dizzy - feels like a ride on a roller coaster for me 😵
You might want to outsource the svgs at some point.

2022-12-06 11:19 UTC, JessicaLoers commented on components/Facility/index.js
> +  line-height: 21px;
```suggestion
  const StyledList = styled.ul`
  text-align: left;
  padding: 0;
  font-size: 1rem;
  line-height: 1.3rem;
```

2022-12-06 11:19 UTC, JessicaLoers commented on components/Facility/index.js
> +
super nitpicking: remove empty lines 🧹

```suggestion
```

2022-12-06 11:19 UTC, JessicaLoers commented on components/Facility/index.js
> +`;
- In the choice of naming, this is a bit weird. But I know that it can be quite complicated to find the right names. 
- When we use negative values it is usually a sign that we should looking for another way to style our element. Maybe you will find a solution - **but this is more a topic for the future Lara**.  🚀

2022-12-06 11:19 UTC, JessicaLoers commented on components/Footer/index.js
>  `;
This the perfect case to style the component dynamically with props. 🤩

```suggestion
  const StyledImage = styled(Image)`
  opacity: ${({ variant }) => (variant === 'active' ? 1 : 0.3)};
`;
```

2022-12-06 11:19 UTC, JessicaLoers commented on components/Footer/index.js
> +          />{" "}
Use props instead of classes 🙂

```suggestion
          <StyledImage
            variant={pathname === "/favorites" ? "active" : "notActive"}
            src={"/assets/svg/favorites.svg"}
            alt={"Favoriten-Icon"}
            width={45}
            height={45}
          />
```

2022-12-06 11:19 UTC, JessicaLoers commented on components/Footer/index.js
> +          />{" "}
```suggestion
          <StyledImage
            variant={pathname === "/favorites" ? "active" : "notActive"}
            src={"/assets/svg/favorites.svg"}
            alt={"Favoriten-Icon"}
            width={45}
            height={45}
          />
```

2022-12-06 11:19 UTC, JessicaLoers commented on components/Footer/index.js
> +          />{" "}
```suggestion
          <StyledImage
            variant={pathname === "/favorites" ? "active" : "notActive"}
            src={"/assets/svg/favorites.svg"}
            alt={"Favoriten-Icon"}
            width={45}
            height={45}
          />
```

2022-12-06 11:19 UTC, JessicaLoers commented on components/Footer/index.js
> +          />{" "}
```suggestion
            variant={pathname === "/medicine" ? "active" : "notActive"}
            src={"/assets/svg/medicine.svg"}
            alt={"Medizin-Icon"}
            width={45}
            height={45}
          />
```

2022-12-06 11:19 UTC, JessicaLoers commented on components/Footer/index.js
> +          />{" "}
```suggestion
          <StyledImage
            variant={pathname === "/hygiene" ? "active" : "notActive"}
            src={"/assets/svg/hygiene.svg"}
            alt={"Hygiene-Icon"}
            width={45}
            height={45}
          />
```

2022-12-06 11:19 UTC, JessicaLoers commented on components/Footer/index.js
> +          />{" "}
Use props to style the components dynamically✌️

```suggestion
          <StyledImage
            variant={pathname === "/sleep" ? "active" : "notActive"}
            src={"/assets/svg/sleep.svg"}
            alt={"Schlafen-Icon"}
            width={45}
            height={45}
          />
```

2022-12-06 11:19 UTC, JessicaLoers commented on components/Footer/index.js
> +
🧹 
```suggestion

```

2022-12-06 11:19 UTC, JessicaLoers commented on components/NavLandingpage/index.js
> +    </>
You don't need the 💎  a.k.a react fragments 

```suggestion
      <StyledNav>
        <StyledNavLink href={"/sleep"}>
          <StyledIcon
            src={"/assets/svg/sleep.svg"}
            alt={"Schlafen-Icon"}
            width={100}
            height={60}
          />
          <StyledSpan>Schlafen</StyledSpan>
        </StyledNavLink>
        <StyledNavLink href={"/hygiene"}>
          <StyledIcon
            src={"/assets/svg/hygiene.svg"}
            alt={"Hygiene-Icon"}
            width={100}
            height={60}
          />
          <StyledSpan>Hygiene</StyledSpan>
        </StyledNavLink>
        <StyledNavLink href={"/medicine"}>
          <StyledIcon
            src={"/assets/svg/medicine.svg"}
            alt={"Medizin-Icon"}
            width={100}
            height={60}
          />
          <StyledSpan>Medizin</StyledSpan>
        </StyledNavLink>
        <StyledNavLink href={"/favorites"}>
          <StyledIcon
            src={"/assets/svg/favorites.svg"}
            alt={"Favoriten-Icon"}
            width={100}
            height={60}
          />
          <StyledSpan>Favoriten</StyledSpan>
        </StyledNavLink>
      </StyledNav>

      <StyledLinkContainer>
        <StyledLink href={"/add"}>Einrichtung hinzufügen</StyledLink>
      </StyledLinkContainer>
```

2022-12-06 11:19 UTC, JessicaLoers commented on components/NavLandingpage/index.js
> +  // margin: 0 10px 10px 10px;
clean code rules 🧹

2022-12-06 11:19 UTC, JessicaLoers commented on components/NavLandingpage/index.js
>  `;
Test the styled in the dev tools and you will see, that you can remove the most of them 🥳

```suggestion
  color: var(--font-color);
  font-size: 1.2rem;
`;
```

2022-12-07 09:56 UTC, EugenMoser approved these changes
looks like a lot of work ;). Good job Lara

2022-12-07 09:56 UTC, EugenMoser commented on components/Header/styled.header.js
>    margin-top: 5px;
I think you can write this in one line 
`margin: 5px 20px 0 0`

2022-12-07 11:30 UTC, merged